# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import usb
import import_data


class Ui_Form(object):
    def __init__(self,main_widget):
        self.model_all_widget = QtWidgets.QWidget(main_widget)
        self.usb_d=usb.usb_drive()

    def get_usb(self):
        self.internet_btn.hide()
        self.cd_btn.hide()
        self.cd_label.hide()
        self.Internet_label.hide()
        self.ok_btn.hide()
        self.sub_title_label.hide()
        self.usb_d.detect_usb(self.model_widget,self.gridLayout,self.ok_btn,self.success_label,self.internet_btn,self.cd_btn,self.sub_title_label)

    def ok_btn_click(self):
        self.sub_title_label.show()
        self.internet_btn.show()
        self.cd_btn.show()
        self.cd_label.show()
        self.Internet_label.show()
        self.ok_btn.hide()
        self.success_label.hide()
        self.usb_d.btn_click()
    def setupUi(self,main_widget,gridLayout_4,main_grid_Layout,main_2_horizontalLayout,verticalLayout):
       
        self.model_all_widget = QtWidgets.QWidget(main_widget)
        self.model_all_widget.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.model_all_widget.setObjectName("model_all_widget")
        self.all_grid_Layout = QtWidgets.QGridLayout(self.model_all_widget)
        self.all_grid_Layout.setContentsMargins(0, 0, 0, 0)
        self.all_grid_Layout.setObjectName("all_grid_Layout")
        self.model_widget = QtWidgets.QWidget(self.model_all_widget)
        self.model_widget.setStyleSheet("\n"
"\n"
"background-color:  rgb(11,11,11);")
        self.model_widget.setObjectName("model_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.model_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # spacerItem3 = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout.addItem(spacerItem3)
        self.main_title_label = QtWidgets.QLabel(self.model_widget)
        self.main_title_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_title_label.setStyleSheet("\n"
"font: 57 16pt \"Poppins Medium\";\n"
"color: rgb(255, 255, 255);\n"
"border-bottom: 3px solid  rgb(72, 72, 72);")
        self.main_title_label.setLineWidth(1)
        self.main_title_label.setTextFormat(QtCore.Qt.AutoText)
        self.main_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_title_label.setObjectName("main_title_label")
        self.horizontalLayout.addWidget(self.main_title_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sub_title_label = QtWidgets.QLabel(self.model_widget)
        self.sub_title_label.setStyleSheet("\n"
"font: 25 15pt \"Poppins \";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.sub_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_title_label.setObjectName("sub_title_label")
        self.horizontalLayout_3.addWidget(self.sub_title_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 2, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 4, 1, 1)
        self.internet_btn = QtWidgets.QPushButton(self.model_widget)
        self.internet_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.internet_btn.clicked.connect(import_data.data_imp)
        self.internet_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"background-color:  rgb(11,11,11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:4.5px;\n"
"border-radius:12px;\n"
"border-color: rgb(182, 182, 182);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"\n"
"/*\n"
"QPushButton{\n"
"background-color:rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:solid ;\n"
"border-width:5px;\n"
"border-radius:0px;\n"
"border-color:rgb(11, 11, 11);\n"
"\n"
"}\n"
"QpushButton:focus{\n"
"\n"
"    border-color: rgb(106, 106, 106);\n"
"}\n"
"*/")
        self.internet_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/internet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.success_label = QtWidgets.QLabel(self.model_widget)
        self.success_label.setStyleSheet("\n"
"font: 25 12pt \"Poppins Light\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.success_label.setAlignment(QtCore.Qt.AlignCenter)
        self.success_label.setObjectName("success_label")
        self.success_label.hide()
        self.horizontalLayout_3.addWidget(self.success_label)
        self.internet_btn.setIcon(icon)
        self.internet_btn.setIconSize(QtCore.QSize(150, 150))
        self.internet_btn.setObjectName("internet_btn")
        self.gridLayout.addWidget(self.internet_btn, 0, 1, 1, 1)
        self.Internet_label = QtWidgets.QLabel(self.model_widget)
        self.Internet_label.setStyleSheet("\n"
"font: 75 12pt \"Poppins\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.Internet_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Internet_label.setObjectName("Internet_label")
        self.gridLayout.addWidget(self.Internet_label, 1, 1, 1, 1)
        self.cd_btn = QtWidgets.QPushButton(self.model_widget)
        self.cd_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cd_btn.clicked.connect(self.get_usb)
        self.cd_btn.setStyleSheet("QPushButton{\n"
"\n"
"background-color:  rgb(11,11,11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:4.5px;\n"
"border-radius:12px;\n"
"border-color: rgb(182, 182, 182);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"")
        self.cd_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/cd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cd_btn.setIcon(icon1)
        self.cd_btn.setIconSize(QtCore.QSize(150, 150))
        self.cd_btn.setObjectName("cd_btn")
        self.gridLayout.addWidget(self.cd_btn, 0, 3, 1, 1)
        self.ok_btn = QtWidgets.QPushButton(self.model_widget)
        self.ok_btn.setMinimumSize(QtCore.QSize(100, 40))
        self.ok_btn.setMaximumSize(QtCore.QSize(100, 40))
        self.ok_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_btn.setGeometry(680, 400, 30, 30)
        self.ok_btn.clicked.connect(self.ok_btn_click)
        self.ok_btn.hide()
        self.ok_btn.setText("OK")
        self.gridLayout.addWidget(self.ok_btn,1,2,1,1)
        self.ok_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(248,180,100);\n"
"color: rgb(0,0,0);\n"
"font: 63 10pt \"Poppins SemiBold\";\n"
"\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:17px;\n"
"padding:6px\n"
"}\n"
"")
        self.cd_label = QtWidgets.QLabel(self.model_widget)
        self.cd_label.setStyleSheet("font: 75 12pt \"Poppins\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.cd_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cd_label.setObjectName("cd_label")
        self.gridLayout.addWidget(self.cd_label, 1, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 250, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.all_grid_Layout.addWidget(self.model_widget, 0, 0, 1, 1)
        gridLayout_4.addWidget(self.model_all_widget, 0, 0, 1, 1)
        main_grid_Layout.addLayout(gridLayout_4, 1, 0, 1, 1)
        main_2_horizontalLayout.addWidget(main_widget)
        verticalLayout.addLayout(main_2_horizontalLayout)

        self.retranslateUi()
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.main_title_label.setText(_translate("Form", "Import new Models / Videos..."))
        self.sub_title_label.setText(_translate("Form", "How would you like to import new Models?"))
        self.Internet_label.setText(_translate("Form", "Internet"))
        self.cd_label.setText(_translate("Form", "CD / USB"))
        self.success_label.setText(_translate("Form", "Import finished succesfully !"))


