# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(839, 565)
        Form.setMinimumSize(QtCore.QSize(839, 565))
        Form.setMaximumSize(QtCore.QSize(839, 565))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_gridLayout = QtWidgets.QGridLayout()
        self.top_gridLayout.setObjectName("top_gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/Untitled_page-0003.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.top_gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.top_gridLayout)
        self.bottom_gridLayout = QtWidgets.QGridLayout()
        self.bottom_gridLayout.setSpacing(0)
        self.bottom_gridLayout.setObjectName("bottom_gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem, 6, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem2, 6, 4, 1, 1)
        self.previous_btn = QtWidgets.QPushButton(Form)
        self.previous_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);\n"
"\n"
"font: 57 10pt \"Poppins \";\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(248, 207, 135);\n"
"}\n"
"")
        self.previous_btn.setObjectName("previous_btn")
        self.bottom_gridLayout.addWidget(self.previous_btn, 6, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem3, 6, 3, 1, 1)
        self.finish_btn = QtWidgets.QPushButton(Form)
        self.finish_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.finish_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(248,180,100);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 57 10pt \"Poppins \";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(248, 207, 135);\n"
"}\n"
"")
        self.finish_btn.setObjectName("finish_btn")
        self.bottom_gridLayout.addWidget(self.finish_btn, 6, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(Form)
        self.path_lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"    font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.path_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.bottom_gridLayout.addWidget(self.path_lineEdit, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.bottom_gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.shortcut_checkBox = QtWidgets.QCheckBox(Form)
        self.shortcut_checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.shortcut_checkBox.setStyleSheet("font: 57 10pt \"Poppins Medium\";\n"
"color: rgb(166, 166, 166);")
        self.shortcut_checkBox.setObjectName("shortcut_checkBox")
        self.bottom_gridLayout.addWidget(self.shortcut_checkBox, 5, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem6, 0, 5, 1, 1)
        self.verticalLayout.addLayout(self.bottom_gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.previous_btn.setText(_translate("Form", "Previous"))
        self.finish_btn.setText(_translate("Form", "Finish"))
        self.label_2.setText(_translate("Form", "Installation Path :"))
        self.shortcut_checkBox.setText(_translate("Form", "Create Desktop Shortcut"))
import xyz_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
