# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_module import *
from PyQt5.QtWidgets import *
import sys
from PyQt5.QtCore import *
from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView,QWebEnginePage as QWebPage
import history_basic


class QLabel_alterada(QLabel):
    clicked=pyqtSignal()

    def mousePressEvent(self, ev):
        self.clicked.emit()

class Ui_Form(object):
    def __init__(self,main_widget):
        self.history_widget = QtWidgets.QWidget(main_widget)
        self.scroll_his_model=QScrollArea()
        self.scroll_his_video=QScrollArea()
        self.vbox1 = QtWidgets.QGridLayout() 
        self.vbox=QtWidgets.QGridLayout()
    
        

    def setupUi(self,main_widget,gridLayout_4,main_grid_Layout,main_2_horizontalLayout,verticalLayout):
        # self.history_widget = QtWidgets.QWidget(main_widget)
        
        self.history_widget.setObjectName("history_widget")
        self.history_widget.show()
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.history_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.history_model_widget = QtWidgets.QWidget(self.scroll_his_model)
        self.history_model_widget.setStyleSheet("background-color: rgb(11,11,11);")
        self.history_model_widget.setObjectName("history_model_widget")
        self.history_model_widget.setLayout(self.vbox1)
        self.horizontalLayout.addWidget(self.scroll_his_model)
        self.history_video_widget = QtWidgets.QWidget(self.scroll_his_video)
        self.history_video_widget.setStyleSheet("background-color: rgb(11,11,11);")
        self.history_video_widget.setObjectName("history_video_widget")
        self.history_video_widget.setLayout(self.vbox)
        self.horizontalLayout.addWidget(self.scroll_his_video)
        # self.scroll_his.setMinimumSize(QtCore.QSize(600, 0))
        # self.scroll_his.setMaximumSize(QtCore.QSize(600, 16777215))
        self.scroll_his_model.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_his_model.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_his_model.setWidgetResizable(True)
        self.scroll_his_model.setStyleSheet("background-color: rgb(36, 36, 36);border:0px;")
        self.scroll_his_model.setWidget(self.history_model_widget)
        self.scroll_his_video.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_his_video.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_his_video.setWidgetResizable(True)
        self.scroll_his_video.setStyleSheet("background-color: rgb(36, 36, 36);border:0px;")
        self.scroll_his_video.setWidget(self.history_video_widget)
        self.his_disp_widget= QtWidgets.QWidget(main_widget)
        self.his_disp_widget.setStyleSheet("background-color: rgb(11,11,11);")
        # self.horizontalLayout.addWidget(self.his_disp_widget)
        self.his_disp_widget.setObjectName("his_disp_widget")
        # self.his_disp_widget.hide()
        self.web=QWebView(self.his_disp_widget)
        gridLayout_4.addWidget(self.history_widget, 0, 0, 1, 1)
        gridLayout_4.addWidget(self.his_disp_widget,0,0,1,1)
        main_grid_Layout.addLayout(gridLayout_4, 2, 0, 1, 1)
        # spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        # main_grid_Layout.addItem(spacerItem4, 1, 0, 1, 1)
#         self.history_label = QtWidgets.QLabel(main_widget)
#         self.history_label.setStyleSheet("color: rgb(255, 255, 255);\n"
# "\n"
# "font: 57 12pt \"Poppins Medium\";\n"
# "\n"
# "")
#         self.history_label.setObjectName("history_label")
#         main_grid_Layout.addWidget(self.history_label, 0, 0, 1, 1)
        main_2_horizontalLayout.addWidget(main_widget)
        verticalLayout.addLayout(main_2_horizontalLayout)
        self.close_btn = QtWidgets.QPushButton(self.his_disp_widget)
        self.close_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb();\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:14px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 11, 11);\n"
"}")
        self.close_btn.setText("")
        self.close_btn.clicked.connect(self.close_web)
        self.close_btn.setIconSize(QtCore.QSize(80, 80))
        self.close_btn.setObjectName("close_btn")
        self.close_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.icon_model=QtGui.QIcon()
        self.icon_model.addPixmap(QtGui.QPixmap("icon/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(self.icon_model)
        self.close_btn.hide()
        # self.retranslateUi()
        self.load_data()
        # self.retranslateUi(Form)
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
        # self.history_label.setText(_translate("Form", "History"))
    def close_web(self):
        self.his_disp_widget.hide()
        # self.scroll_his_model.show()
        # self.scroll_his_video.show()
        self.history_widget.show()

    def video_render(self,num,id):
        history_basic.count_history(id,'video')
       
        f = open('c:/xampp/htdocs/main_data/index1.html','w')
        html_template =f"""<html>

<head>
     <link rel="stylesheet" type="text/css" href="demo.css">

</head>

<body>
    <video controls id="myvideo">
  <source src="{str(num)}" type="video/webm">
   <source src="small.ogg" type="video/ogg">

</video>


</body>

</html>"""
        f.write(html_template)
        f.close()
        self.url=f"http://localhost/main_data/index1.html"
        self.web.load(QUrl(self.url))
        self.web.setGeometry(QtCore.QRect(0, 0, 1600, 830))
        self.close_btn.show()
        self.close_btn.setGeometry(QtCore.QRect(1560, 0, 30, 30))
        # self.scroll_his_model.hide()
        # self.scroll_his_video.hide()
        self.history_widget.hide()
        self.his_disp_widget.show()

    def model_render(self,num,id):
        history_basic.count_history(id,'model')
        # self.scroll_his_model.hide()
        # self.scroll_his_video.hide()
        self.history_widget.hide()
        self.his_disp_widget.show()
        self.url=f"http:/localhost/main_data/{str(num)}"
        self.web.load(QUrl(self.url))
        self.web.setGeometry(QtCore.QRect(0, 0, 1600, 830))
        # self.web.show()
        self.close_btn.show()
        self.close_btn.setGeometry(QtCore.QRect(1560, 0, 30, 30))
        
        # self.history_widget.hide()
         
    def fun(self,num,num1,id):
        self.object[num].clicked.connect(lambda:self.video_render(str(num1),id))
   
    def fun1(self,num,num1,id):
        self.object1[num].clicked.connect(lambda:self.model_render(str(num1),id))
    def load_data(self):
        self.history_widget.show()
        self.his_disp_widget.hide()
        sql=f"SELECT * FROM history ORDER BY date_time DESC"
        mycursor.execute(sql)
        myresult2=mycursor.fetchall()
        model=[]
        video=[]
        self.result=[]
        self.result1=[]
        self.object1=[]
        self.object=[]
        myresult=[]
        myresult1=[]
        for i in range(0,len(myresult2)):
            if(myresult2[i][2]=='model'):
                model.append(myresult2[i][1])
            elif(myresult2[i][2]=='video'):
                video.append(myresult2[i][1])
        if(model!=[]):
            for i in model:
                sql=f'SELECT * FROM model_file WHERE id={i}'
                mycursor.execute(sql)
                myresult=mycursor.fetchall()
                self.result.append(myresult[0])
                self.object1.append(QLabel_alterada(self.history_model_widget))
            for j in range(0,len(self.result)):
                for y in range(2):
                    self.object1[j] = QLabel_alterada(self.history_model_widget)
                    self.object1[j].setText(f"{self.result[j][4]}\n{self.result[j][7]}")
                    self.object1[j].setMinimumSize(300,40)
                    self.object1[j].setStyleSheet("color:white;font: 25 9pt \"Poppins Medium\";")
                    self.object1[j].setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
                    self.object1[j].setScaledContents(True)
                    self.vbox1.addWidget(self.object1[j],j,y)
                    # self.object1[i].clicked.connect(self.home1)
                    self.object1[j].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                    if(y==0):
                            self.object1[j].setPixmap(QtGui.QPixmap(f"C:/xampp/htdocs/main_data/{self.result[j][6]}"))
                            self.object1[j].setMinimumSize(QtCore.QSize(350, 200))
                            self.fun1(j,self.result[j][5],self.result[j][0])

        
        if(video!=[]):
            for k in video:
                sql1=f'SELECT * FROM video WHERE id={k}'
                mycursor.execute(sql1)
                myresult1=mycursor.fetchall()
                self.result1.append(myresult1[0])
                self.object.append(QLabel_alterada(self.history_video_widget))
            for j in range(0,len(self.result1)):
                for y in range(2):
                    self.object[j] = QLabel_alterada(self.history_video_widget)
                    self.object[j].setText(f"{self.result1[j][4]}\n{self.result1[j][7]}")
                    self.object[j].setMinimumSize(300,40)
                    self.object[j].setStyleSheet("color:white;font: 25 9pt \"Poppins Medium\";")
                    self.object[j].setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
                    self.object[j].setScaledContents(True)
                    self.vbox.addWidget(self.object[j],j,y)
                    # self.object1[i].clicked.connect(self.home1)
                    self.object[j].setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                    if(y==0):
                            self.object[j].setPixmap(QtGui.QPixmap(f"C:/xampp/htdocs/main_data/{self.result1[j][6]}"))
                            self.object[j].setMinimumSize(QtCore.QSize(350, 200))
                            self.fun(j,self.result1[j][5],self.result1[j][0])