# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_Form(object):
    def setupUi(self, Form):

        # this will hide the title bar
        Form.setWindowFlag(Qt.FramelessWindowHint)
        
        Form.setObjectName("Form")
        Form.resize(842, 566)
        Form.setMinimumSize(QtCore.QSize(842, 566))
        Form.setMaximumSize(QtCore.QSize(842, 566))
        Form.setStyleSheet("background-image: url(:/newPrefix/icon/3d-01.png);\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.start_progressBar = QtWidgets.QProgressBar(Form)
        self.start_progressBar.setStyleSheet("\n"
"\n"
"QProgressBar\n"
"{\n"
"\n"
"background-image: url(:/newPrefix/icon/text.png);\n"
"    background-color: rgb(53, 53, 53);\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"border-style:solid;\n"
"border-align:center;\n"
"border-radius :10px;\n"
"\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"background-color:rgb(248,180,100);\n"
"border-radius :10px;\n"
"}  ")
        self.start_progressBar.setProperty("value", 100)
        self.start_progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.start_progressBar.setObjectName("start_progressBar")
        self.gridLayout.addWidget(self.start_progressBar, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 4, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 3, 1, 1)
        self.version_label = QtWidgets.QLabel(Form)
        self.version_label.setStyleSheet("\n"
"background-image: url(:/newPrefix/icon/text.png);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 11pt \"Poppins\";")
        self.version_label.setObjectName("version_label")
        self.gridLayout.addWidget(self.version_label, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(270, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.version_label.setText(_translate("Form", "V .1.0"))
import xyz_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
