# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo6.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_module import *
from PyQt5.QtWidgets import *
import sys
from PyQt5.QtCore import *
from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView,QWebEnginePage as QWebPage
import history_basic


class Ui_Form(object):
    def __init__(self,main_widget):
        self.search_widget = QtWidgets.QWidget(main_widget)
        self.scroll_search_model=QScrollArea()
        self.scroll_search_video=QScrollArea()
        self.vbox1 = QtWidgets.QGridLayout() 
        self.vbox=QtWidgets.QGridLayout()
    def setupUi(self,main_widget,gridLayout_4,main_grid_Layout,main_2_horizontalLayout,verticalLayout):
        
        self.search_widget.show()
        self.search_widget.setObjectName("search_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_model_widget = QtWidgets.QWidget()
        self.search_model_widget.setLayout(self.vbox1)
        self.search_model_widget.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.search_model_widget.setObjectName("search_model_widget")
        self.horizontalLayout.addWidget(self.scroll_search_model)
        self.search_video_widget = QtWidgets.QWidget()
        self.search_video_widget.setLayout(self.vbox)
        self.search_video_widget.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.search_video_widget.setObjectName("search_video_widget")
        self.horizontalLayout.addWidget(self.scroll_search_video)
        gridLayout_4.addWidget(self.search_widget, 0, 0, 1, 1)
        main_grid_Layout.addLayout(gridLayout_4, 2, 0, 1, 1)
        self.scroll_search_model.setWidget(self.search_model_widget)
        self.scroll_search_video
        # spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        # main_grid_Layout.addItem(spacerItem4, 1, 0, 1, 1)
#         self.search_label = QtWidgets.QLabel(main_widget)
#         self.search_label.setStyleSheet("color: rgb(255, 255, 255);\n"
# "\n"
# "font: 57 12pt \"Poppins Medium\";\n"
# "\n"
# "")
#         self.search_label.setObjectName("search_label")
        # main_grid_Layout.addWidget(self.search_label, 0, 0, 1, 1)
        main_2_horizontalLayout.addWidget(main_widget)
        verticalLayout.addLayout(main_2_horizontalLayout)

        self.retranslateUi()
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # self.search_label.setText(_translate("Form", "Search"))
import xyz_rc

