# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(839, 565)
        Form.setMinimumSize(QtCore.QSize(839, 565))
        Form.setMaximumSize(QtCore.QSize(839, 565))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_gridLayout = QtWidgets.QGridLayout()
        self.top_gridLayout.setObjectName("top_gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/ABCD_page-0002.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.top_gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.top_gridLayout)
        self.bottom_gridLayout = QtWidgets.QGridLayout()
        self.bottom_gridLayout.setSpacing(0)
        self.bottom_gridLayout.setObjectName("bottom_gridLayout")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.bottom_gridLayout.addWidget(self.label_6, 7, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem, 10, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.bottom_gridLayout.addWidget(self.label, 9, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setStyleSheet("\n"
"color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"\n"
"\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.bottom_gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.bottom_gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem4, 4, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem5, 8, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem6, 6, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem7, 1, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 270, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem8, 10, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.bottom_gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(Form)
        self.name_lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.bottom_gridLayout.addWidget(self.name_lineEdit, 0, 3, 1, 1)
        self.state_lineEdit = QtWidgets.QLineEdit(Form)
        self.state_lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.state_lineEdit.setObjectName("state_lineEdit")
        self.bottom_gridLayout.addWidget(self.state_lineEdit, 3, 3, 1, 1)
        self.city_lineEdit = QtWidgets.QLineEdit(Form)
        self.city_lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.city_lineEdit.setObjectName("city_lineEdit")
        self.bottom_gridLayout.addWidget(self.city_lineEdit, 5, 3, 1, 1)
        self.pincode_lineEdit = QtWidgets.QLineEdit(Form)
        self.pincode_lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.pincode_lineEdit.setObjectName("pincode_lineEdit")
        self.bottom_gridLayout.addWidget(self.pincode_lineEdit, 7, 3, 1, 1)
        self.address_textEdit = QtWidgets.QTextEdit(Form)
        self.address_textEdit.setStyleSheet("\n"
"\n"
"\n"
"QTextEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"    font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QTextEdit:focus{\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"\n"
"}")
        self.address_textEdit.setObjectName("address_textEdit")
        self.bottom_gridLayout.addWidget(self.address_textEdit, 9, 3, 1, 1)
        self.next_btn = QtWidgets.QPushButton(Form)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("QPushButton{\n"
"background-color:  rgb(248,180,100);\n"
"color: rgb(255, 255, 255);\n"
"font: 57 10pt \"Poppins \";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(248, 207, 135);\n"
"}\n"
"")
        self.next_btn.setObjectName("next_btn")
        self.bottom_gridLayout.addWidget(self.next_btn, 10, 4, 1, 1)
        self.verticalLayout.addLayout(self.bottom_gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Pin Code :"))
        self.label.setText(_translate("Form", "Full Address :"))
        self.label_2.setText(_translate("Form", "Your Name :"))
        self.label_5.setText(_translate("Form", "City :"))
        self.label_4.setText(_translate("Form", "State :"))
        self.next_btn.setText(_translate("Form", "Next"))
import xyz_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
