# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from pickle import TRUE
from ffpyplayer.player import MediaPlayer
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from  db_module import *
from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView,QWebEnginePage as QWebPage
from PyQt5.QtWebEngineWidgets import QWebEngineSettings as QWebSettings
from PyQt5.QtNetwork import *
from PyQt5.QtCore import QUrl
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PIL import Image
import numpy
import threading
import time
import cv2
import os
class VideoPlayer:
    def __init__(self, filename,volume = 1.0):
        if not os.path.exists(filename):raise FileNotFound(filename)
        self.close = False
        self.state = None
        self.frame = None
        self.l=None
        self.filename = filename
        self.skip_interval=5

        self.player = MediaPlayer(filename, ff_opts={'sync': 'audio', 'paused': False, 'volume': volume, 't': 1e7+1, 'ss': 0})
        time.sleep(1)
        self.duration=self.player.get_metadata()['duration']
        handler_thread = threading.Thread(target=self.play, args=(), daemon=True)
        handler_thread.start()

    def play(self):
        while True:
            frame, self.val = self.player.get_frame()
            if self.val == 'eof':self.close=True
            if self.close == True:
                self.player.toggle_pause()
                self.player.close_player()
                time.sleep(2)
                break

            if isinstance(self.val, str) or self.val == 0.0:waitkey = 32
            else:waitkey = int(self.val * 100)
            pressed_key = cv2.waitKey(waitkey) & 0xFF

            if frame is None:continue

            image, pts = frame
            self.frame = (image, self.val)
            x, y = image.get_size()
            data = image.to_bytearray()[0]
            image =  Image.frombytes("RGB", (x, y), bytes(data))
            image = cv2.cvtColor(numpy.array(image), cv2.COLOR_RGB2BGR)
            self.frame=frame

            if self.l!=None:
                h, w, ch = image.shape
                Image2 = QImage(image.data, w, h, ch * w, QImage.Format_RGB888)
                self.pixmap=QPixmap.fromImage(Image2)
                self.l.setPixmap(self.pixmap)
                self.l.setFixedWidth(self.l.pixmap().width())
                self.l.setFixedHeight(self.l.pixmap().height())
                # self.l.parent().update()
            del image


    def seek_p(self):
            if int(self.player.get_pts()) + self.skip_interval < int(self.duration):
                self.player.seek(self.skip_interval, relative=True, accurate=False)
    def seek_m(self):
        if int(self.player.get_pts()) - self.skip_interval > 0:
            self.player.seek(-self.skip_interval, relative=True, accurate=False)

class ed(QWidget):
    def __init__(self,parent=None):
        super().__init__()
        vl=QVBoxLayout()
        self.setLayout(vl)
        pb=QPushButton('play');vl.addWidget(pb);pb.clicked.connect(self.play)
        pb=QPushButton('stop');vl.addWidget(pb);pb.clicked.connect(self.close)
        pb=QPushButton('pause');vl.addWidget(pb);pb.clicked.connect(self.pause)
        pb=QPushButton('seek+');vl.addWidget(pb);pb.clicked.connect(self.seek_p)
        pb=QPushButton('seek-');vl.addWidget(pb);pb.clicked.connect(self.seek_m)
        pb=QPushButton('mute');vl.addWidget(pb);pb.clicked.connect(self.mute)
        pb=QPushButton('vol+');vl.addWidget(pb);pb.clicked.connect(self.vol_p)
        pb=QPushButton('vol-');vl.addWidget(pb);pb.clicked.connect(self.vol_m)
        self.l=QLabel();vl.addWidget(self.l)
    def play2(self):
        self.player=VideoPlayer('icon/video1.mp4')
        self.player.l=self.l

    def play(self):
        self.t1=threading.Thread(target=self.play2)
        self.t1.start()

    def pause(self):self.player.player.toggle_pause()
    def seek_p(self):self.player.seek_p()
    def seek_m(self):self.player.seek_m()
    def mute(self):
        try:
            if (self.player.player.get_volume()>0.0):self.player.player.set_volume(0.0)
            else:self.player.player.set_volume(1.0)
        except:pass
    def vol_p(self):
        self.player.player.set_volume(self.player.player.get_volume() + 0.1)
        print(self.player.player.get_volume())
    def vol_m(self):
        self.player.player.set_volume(self.player.player.get_volume() - 0.1)
        print(self.player.player.get_volume())

    def close(self):
        try:
            self.player.close=True
            time.sleep(1)
        except:pass

    def closeEvent(self, event):
        try:
            self.player.close=True
            time.sleep(1)
        except:pass
     
class QLabel_alterada(QLabel):
    clicked=pyqtSignal()

    def mousePressEvent(self, ev):
        self.clicked.emit()

class Ui_Form(object):
    def __init__(self):
        self.state_model=1
        self.icon_model=QtGui.QIcon()
        

############################################ all function ####################################################################
    
    def imports(self):
        f=open()

    def home(self):
        self.home_btn.setChecked(True)
        self.home_btn.setCheckable(True)
        self.sql=f"SELECT filename FROM model_file WHERE id=11"
        mycursor.execute(self.sql)
        self.myresult = mycursor.fetchall()
        self.url="http:/localhost/"+self.myresult[0][0]
        self.web.load(QUrl(self.url))
        self.web.setGeometry(QtCore.QRect(0, 0, 1050, 380))
        self.max_model.setGeometry(QtCore.QRect(1010, 410, 30, 30))
        self.max_model.raise_()
        self.max_model.show()
        self.icon_model.addPixmap(QtGui.QPixmap("icon/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_model.setIcon(self.icon_model)
        self.model=[]
    def play(self):
        self.t1=threading.Thread(target=self.home)
        self.t1.start()

    def home1(self):
        self.web.load(QUrl("file:///C:/xampp/htdocs/v1/index.html"))    
        self.web.setGeometry(QtCore.QRect(0, 0, 1050, 380))
        self.max_model.setGeometry(QtCore.QRect(1010, 410, 30, 30))
        self.max_model.raise_()
        self.max_model.show()
        self.icon_model.addPixmap(QtGui.QPixmap("icon/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_model.setIcon(self.icon_model)
        
    def size_model(self):
        if(self.state_model==1):
          self.model_widget.setMinimumSize(900,750)
          self.max_model.setGeometry(QtCore.QRect(1620, 0, 30, 30))
          self.web.setGeometry(QtCore.QRect(0, 0, 1650, 750))
          self.right_widget.hide()
          self.bottom_widget.hide()
          self.icon_model.addPixmap(QtGui.QPixmap("icon/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          self.max_model.setIcon(self.icon_model)
          self.scroll_right.hide()
          self.scroll.hide()
          self.state_model=0
        elif(self.state_model==0):
          self.model_widget.setMinimumSize(900,450)
          self.icon_model.addPixmap(QtGui.QPixmap("icon/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
          self.max_model.setIcon(self.icon_model)
          self.web.setGeometry(QtCore.QRect(0, 0, 1050, 380))
          self.max_model.setGeometry(QtCore.QRect(1010, 410, 30, 30))
          self.max_model.raise_()
          self.max_model.show()
          self.right_widget.show()
          self.bottom_widget.show()
          self.scroll.show()
          self.scroll_right.show()
          self.state_model=1

    def setupUi(self, Form):
        
        
########################################### all declrations #####################################################
        
################################## main form ########################################################################
        Form.setObjectName("Form")
        Form.resize(982, 660)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_1_horizontalLayout = QtWidgets.QHBoxLayout()
        self.main_1_horizontalLayout.setObjectName("main_1_horizontalLayout")
###################################### top frame ############################################################################

        self.top_frame = QtWidgets.QFrame(Form)
        self.top_frame.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"\n"
"\n"
"border-bottom: 3px solid  rgb(72, 72, 72);\n"
"/*background-color: rgb(135, 135, 135);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.top_frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"padding-left:5%;\n"
"/*background-color: rgb(36, 36, 36);*/\n"
"\n"
"border-bottom: 2px solid  rgb(36, 36, 36);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.top_frame)
        self.lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color:rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:15px;\n"
"border-color:rgb(11, 11, 11);\n"
"\n"
"padding:6px\n"
"}\n"
"QLineEdit:focus{\n"
"\n"
"    border-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.search_btn = QtWidgets.QPushButton(self.top_frame)
        self.search_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:14px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}")
        self.search_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon)
        self.search_btn.setObjectName("search_btn")
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.search_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.import_btn = QtWidgets.QPushButton(self.top_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.import_btn.sizePolicy().hasHeightForWidth())
        self.import_btn.setSizePolicy(sizePolicy)
        self.import_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.import_btn.clicked.connect(self.imports)
        self.import_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.import_btn.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.import_btn.setIconSize(QtCore.QSize(16, 16))
        self.import_btn.setObjectName("import_btn")
        self.horizontalLayout.addWidget(self.import_btn)
        self.setting_btn = QtWidgets.QPushButton(self.top_frame)
        self.setting_btn.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px")
        self.setting_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon1)
        self.setting_btn.setIconSize(QtCore.QSize(50, 50))
        self.setting_btn.setObjectName("setting_btn")
        self.setting_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.setting_btn)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.main_1_horizontalLayout.addWidget(self.top_frame)
        self.verticalLayout.addLayout(self.main_1_horizontalLayout)
        self.main_2_horizontalLayout = QtWidgets.QHBoxLayout()
        self.main_2_horizontalLayout.setSpacing(0)
        self.main_2_horizontalLayout.setObjectName("main_2_horizontalLayout")
######################################## left widgets #####################################################################################
        self.left_widget = QtWidgets.QWidget(Form)
        self.left_widget.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn = QtWidgets.QPushButton(self.left_widget)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:50px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon2)
        self.home_btn.setIconSize(QtCore.QSize(15, 35))
        self.home_btn.setCheckable(False)
        self.home_btn.setAutoDefault(False)
        self.home_btn.setObjectName("home_btn")
        self.home_btn.clicked.connect(self.home)
        self.verticalLayout_2.addWidget(self.home_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.popular_btn = QtWidgets.QPushButton(self.left_widget)
        self.popular_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.popular_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:40px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/popular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.popular_btn.setIcon(icon3)
        self.popular_btn.setIconSize(QtCore.QSize(10, 35))
        self.popular_btn.setAutoDefault(False)
        self.popular_btn.setDefault(False)
        self.popular_btn.setFlat(False)
        self.popular_btn.setObjectName("popular_btn")
        self.verticalLayout_2.addWidget(self.popular_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem3)
        self.history_btn_2 = QtWidgets.QPushButton(self.left_widget)
        self.history_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_btn_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:50px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_btn_2.setIcon(icon4)
        self.history_btn_2.setIconSize(QtCore.QSize(50, 50))
        self.history_btn_2.setObjectName("history_btn_2")
        self.verticalLayout_2.addWidget(self.history_btn_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem4)
        self.categories_btn = QtWidgets.QPushButton(self.left_widget)
        self.categories_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.categories_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:25px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/categories.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.categories_btn.setIcon(icon5)
        self.categories_btn.setIconSize(QtCore.QSize(35, 35))
        self.categories_btn.setObjectName("categories_btn")
        self.verticalLayout_2.addWidget(self.categories_btn)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem5)
        self.favorites_btn = QtWidgets.QPushButton(self.left_widget)
        self.favorites_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favorites_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:35px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/favorites.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favorites_btn.setIcon(icon6)
        self.favorites_btn.setIconSize(QtCore.QSize(40, 35))
        self.favorites_btn.setObjectName("favorites_btn")
        self.verticalLayout_2.addWidget(self.favorites_btn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.label_2 = QtWidgets.QLabel(self.left_widget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left:5%;\n"
"font: 75 italic 16pt \"Perpetua\";\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem8)
        self.mathematics_btn = QtWidgets.QPushButton(self.left_widget)
        self.mathematics_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mathematics_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:30px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/mathematics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mathematics_btn.setIcon(icon7)
        self.mathematics_btn.setIconSize(QtCore.QSize(40, 35))
        self.mathematics_btn.setObjectName("mathematics_btn")
        self.verticalLayout_2.addWidget(self.mathematics_btn)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem9)
        self.history_sub_btn = QtWidgets.QPushButton(self.left_widget)
        self.history_sub_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_sub_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:65px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/history_sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_sub_btn.setIcon(icon8)
        self.history_sub_btn.setIconSize(QtCore.QSize(35, 35))
        self.history_sub_btn.setObjectName("history_sub_btn")
        self.verticalLayout_2.addWidget(self.history_sub_btn)
        spacerItem10 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem10)
        self.science_btn = QtWidgets.QPushButton(self.left_widget)
        self.science_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.science_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:65px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/science.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.science_btn.setIcon(icon9)
        self.science_btn.setIconSize(QtCore.QSize(40, 35))
        self.science_btn.setObjectName("science_btn")
        self.verticalLayout_2.addWidget(self.science_btn)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem11)
        self.arts_btn = QtWidgets.QPushButton(self.left_widget)
        self.arts_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arts_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:90px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/arts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arts_btn.setIcon(icon10)
        self.arts_btn.setIconSize(QtCore.QSize(35, 35))
        self.arts_btn.setObjectName("arts_btn")
        self.arts_btn.clicked.connect(self.home1)
        self.verticalLayout_2.addWidget(self.arts_btn)
        spacerItem12 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem12)
        self.label_4 = QtWidgets.QLabel(self.left_widget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 16pt \"Perpetua\";\n"
"padding-left:5%;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem13)
############################################### std widget ############################################################################
        self.standards_widget = QtWidgets.QWidget(self.left_widget)
        self.standards_widget.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.standards_widget.setObjectName("standards_widget")
        self.standards_vertical_Layout = QtWidgets.QVBoxLayout(self.standards_widget)
        self.standards_vertical_Layout.setContentsMargins(0, 0, 0, 0)
        self.standards_vertical_Layout.setSpacing(0)
        self.standards_vertical_Layout.setObjectName("standards_vertical_Layout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.standards_vertical_Layout.addLayout(self.verticalLayout_14)
        self.verticalLayout_2.addWidget(self.standards_widget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.main_2_horizontalLayout.addWidget(self.left_widget)
#################################### main widget ######################################################################################
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.main_widget.setObjectName("main_widget")
        self.main_grid_Layout = QtWidgets.QGridLayout(self.main_widget)
        self.main_grid_Layout.setContentsMargins(9, 9, 9, 9)
        self.main_grid_Layout.setObjectName("main_grid_Layout")
        # self.widget_2 = QtWidgets.QWidget(self.main_widget)
        # # self.widget_2.setObjectName("widget_2")
        # self.main_grid_Layout.addWidget(self.widget_2, 4, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mange_widget = QtWidgets.QWidget(self.main_widget)
        self.mange_widget.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.mange_widget.setObjectName("mange_widget")
        self.gridLayout_4.addWidget(self.mange_widget, 1, 1, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem15, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem16, 0, 1, 1, 1)
################################ all widget ####################################################################################

        self.all_widget = QtWidgets.QWidget(self.main_widget)
        self.all_widget.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.all_widget.setObjectName("all_widget")
        self.all_grid_Layout = QtWidgets.QGridLayout(self.all_widget)
        self.all_grid_Layout.setContentsMargins(0, 0, 0, 0)
        self.all_grid_Layout.setObjectName("all_grid_Layout")
############################# right widget ####################################################################

#         self.right_widget = QtWidgets.QWidget(self.all_widget)
#         self.scroll_right = QScrollArea() 
#         # self.vbox1 = QtWidgets.QGridLayout() 
#         self.right_widget.setMinimumSize(QtCore.QSize(600, 0))
#         self.right_widget.setMaximumSize(QtCore.QSize(600, 16777215))
#         self.right_widget.setStyleSheet("\n"
# "background-color: rgb(255, 170, 255);")
#         self.right_widget.setObjectName("right_widget")
#         # self.right_widget.setLayout(self.vbox1)
#         # self.right_vertical_Layout = QtWidgets.QVBoxLayout(self.right_widget)
#         # self.right_vertical_Layout.setContentsMargins(0, 0, 0, 0)
#         # self.right_vertical_Layout.setSpacing(0)
#         # self.right_vertical_Layout.setObjectName("right_vertical_Layout")
#         self.verticalLayout_4 = QtWidgets.QGridLayout()
#         self.verticalLayout_4.setObjectName("verticalLayout_4")
#         # spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
#         # self.verticalLayout_4.addItem(spacerItem17)
#         # self.right_vertical_Layout.addLayout(self.right_widget)
#         self.scroll_right.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
#         self.scroll_right.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
#         self.scroll_right.setWidgetResizable(True)
#         self.scroll_right.setWidget(self.right_widget)
#         self.all_grid_Layout.addWidget(self.scroll_right, 0, 1, 2, 1)
        self.scroll_right=QScrollArea(self.all_widget)
        self.vbox1 = QtWidgets.QGridLayout() 
        self.right_widget = QtWidgets.QWidget()
        self.right_widget.setLayout(self.vbox1)
        self.scroll_right.setMinimumSize(QtCore.QSize(600, 0))
        self.scroll_right.setMaximumSize(QtCore.QSize(600, 16777215))
        self.scroll_right.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scroll_right.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll_right.setWidgetResizable(True)
        self.scroll_right.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.scroll_right.setWidget(self.right_widget)
        self.all_grid_Layout.addWidget(self.scroll_right,  0, 1, 2, 1)
       

########################################## model widget #####################################################################

        self.model_widget = QtWidgets.QWidget(self.all_widget)
        self.web=QWebView(self.model_widget)
        self.model_widget.setStyleSheet("\n"
"background-color: rgb(36, 36, 36);")
        self.model_widget.setObjectName("model_widget")
        self.all_grid_Layout.addWidget(self.model_widget, 0, 0, 1, 1)
        self.model_widget.setMinimumSize(900,450)
        # self.mbox1=QGridLayout(self.model_widget)
        # self.l=QLabel();self.mbox1.addWidget(self.l)
        spacerItem201 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        # self.mbox1.addItem(spacerItem201)
        
        
######################################## bottom widget ########################################################################
        self.bottom_widget = QtWidgets.QWidget(self.all_widget)
        self.scroll = QScrollArea() 
        self.vbox = QtWidgets.QGridLayout() 
        self.bottom_widget.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.bottom_widget.setObjectName("bottom_widget")
        # self.all_grid_Layout.addWidget(self.bottom_widget, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.all_widget, 0, 0, 1, 1)
        self.main_grid_Layout.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.bottom_widget.setLayout(self.vbox)
        spacerItem20 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.vbox.addItem(spacerItem20)
        self.scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scroll.setWidgetResizable(True)
        self.scroll.setWidget(self.bottom_widget)
        self.all_grid_Layout.addWidget(self.scroll, 1, 0, 1, 1)


########################################## subject widget #######################################################################
        self.subject_widget = QtWidgets.QWidget(self.main_widget)
        self.subject_widget.setMinimumSize(QtCore.QSize(100, 50))
        self.subject_widget.setStyleSheet("color: rgb(255, 255, 255);")
        self.subject_widget.setObjectName("subject_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.subject_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.subject_horizontal_Layout = QtWidgets.QHBoxLayout()
        self.subject_horizontal_Layout.setObjectName("subject_horizontal_Layout")
        self.language_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.language_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.language_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.language_btn_2.setObjectName("language_btn_2")
        self.subject_horizontal_Layout.addWidget(self.language_btn_2)
        self.biology_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.biology_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.biology_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.biology_btn_2.setObjectName("biology_btn_2")
        self.subject_horizontal_Layout.addWidget(self.biology_btn_2)
        self.evs_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.evs_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.evs_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.evs_btn_2.setObjectName("evs_btn_2")
        self.subject_horizontal_Layout.addWidget(self.evs_btn_2)
        self.physics_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.physics_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.physics_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.physics_btn_2.setObjectName("physics_btn_2")
        self.subject_horizontal_Layout.addWidget(self.physics_btn_2)
        self.history_sub2_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.history_sub2_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_sub2_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.history_sub2_btn_2.setObjectName("history_sub2_btn_2")
        self.subject_horizontal_Layout.addWidget(self.history_sub2_btn_2)
        self.maths_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.maths_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maths_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.maths_btn_2.setObjectName("maths_btn_2")
        self.subject_horizontal_Layout.addWidget(self.maths_btn_2)
        self.horizontalLayout_4.addLayout(self.subject_horizontal_Layout)
        self.main_grid_Layout.addWidget(self.subject_widget, 2, 1, 1, 2)
        self.explore_by_subject = QtWidgets.QLabel(self.main_widget)
        self.explore_by_subject.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.explore_by_subject.setObjectName("explore_by_subject")
        self.main_grid_Layout.addWidget(self.explore_by_subject, 0, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.main_grid_Layout.addItem(spacerItem18, 1, 1, 1, 1)
        self.main_2_horizontalLayout.addWidget(self.main_widget)
        self.verticalLayout.addLayout(self.main_2_horizontalLayout)
############################################### all declration ####################################################################
        self.max_model = QtWidgets.QPushButton(self.model_widget)
        self.max_model.hide()
        self.max_model.setStyleSheet("QPushButton{\n"
"background-color: rgb();\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:14px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(11, 11, 11);\n"
"}")
        self.max_model.setText("")
        self.max_model.clicked.connect(self.size_model)
        self.max_model.setIconSize(QtCore.QSize(80, 80))
        self.max_model.setObjectName("max_model")
        self.max_model.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Education 3D"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Search"))
        self.import_btn.setText(_translate("Form", "Import  Models"))
        self.home_btn.setText(_translate("Form", "   Home"))
        self.popular_btn.setText(_translate("Form", "   Popular"))
        self.history_btn_2.setText(_translate("Form", " History "))
        self.categories_btn.setText(_translate("Form", "  Categories "))
        self.favorites_btn.setText(_translate("Form", "  Favorites "))
        self.label_2.setText(_translate("Form", "CATEGORIES"))
        self.mathematics_btn.setText(_translate("Form", "  Mathematics "))
        self.history_sub_btn.setText(_translate("Form", "   History "))
        self.science_btn.setText(_translate("Form", "  Science "))
        self.arts_btn.setText(_translate("Form", "  Arts "))
        self.label_4.setText(_translate("Form", "STANDARDS"))
        self.language_btn_2.setText(_translate("Form", "LANGUAGE"))
        self.biology_btn_2.setText(_translate("Form", "BIOLOGY"))
        self.evs_btn_2.setText(_translate("Form", "EVS"))
        self.physics_btn_2.setText(_translate("Form", "PHYSICS"))
        self.history_sub2_btn_2.setText(_translate("Form", "HISTORY"))
        self.maths_btn_2.setText(_translate("Form", "MATHS"))
        self.explore_by_subject.setText(_translate("Form", "Explore by Subjects"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())