# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(970, 956)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_1_horizontalLayout = QtWidgets.QHBoxLayout()
        self.main_1_horizontalLayout.setObjectName("main_1_horizontalLayout")
        self.top_frame = QtWidgets.QFrame(Form)
        self.top_frame.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"\n"
"\n"
"border-bottom: 3px solid  rgb(72, 72, 72);\n"
"/*background-color: rgb(135, 135, 135);")
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.top_frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 15pt \"MS Shell Dlg 2\";\n"
"\n"
"/*background-color: rgb(36, 36, 36);*/\n"
"\n"
"border-bottom: 2px solid  rgb(36, 36, 36);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(50, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.top_frame)
        self.lineEdit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color:rgb(11, 11, 11);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:15px;\n"
"border-color:rgb(11, 11, 11);\n"
"\n"
"padding:6px\n"
"}\n"
"QLineEdit:focus{\n"
"\n"
"    border-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.top_frame)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:14px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.top_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"font: 13pt \"MS Shell Dlg 2\";\n"
"\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.top_frame)
        self.pushButton.setStyleSheet("background-color: rgb(36, 36, 36);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:15px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.main_1_horizontalLayout.addWidget(self.top_frame)
        self.verticalLayout.addLayout(self.main_1_horizontalLayout)
        self.main_2_horizontalLayout = QtWidgets.QHBoxLayout()
        self.main_2_horizontalLayout.setSpacing(0)
        self.main_2_horizontalLayout.setObjectName("main_2_horizontalLayout")
        self.left_widget = QtWidgets.QWidget(Form)
        self.left_widget.setStyleSheet("background-color: rgb(36, 36, 36);")
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home_btn = QtWidgets.QPushButton(self.left_widget)
        self.home_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:50px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon2)
        self.home_btn.setIconSize(QtCore.QSize(15, 35))
        self.home_btn.setCheckable(False)
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout_2.addWidget(self.home_btn)
        self.popular_btn = QtWidgets.QPushButton(self.left_widget)
        self.popular_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.popular_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:40px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/popular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.popular_btn.setIcon(icon3)
        self.popular_btn.setIconSize(QtCore.QSize(10, 35))
        self.popular_btn.setAutoDefault(False)
        self.popular_btn.setDefault(False)
        self.popular_btn.setFlat(False)
        self.popular_btn.setObjectName("popular_btn")
        self.verticalLayout_2.addWidget(self.popular_btn)
        self.history_btn_2 = QtWidgets.QPushButton(self.left_widget)
        self.history_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_btn_2.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:50px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_btn_2.setIcon(icon4)
        self.history_btn_2.setIconSize(QtCore.QSize(35, 35))
        self.history_btn_2.setObjectName("history_btn_2")
        self.verticalLayout_2.addWidget(self.history_btn_2)
        self.categories_btn = QtWidgets.QPushButton(self.left_widget)
        self.categories_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.categories_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:25px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/categories.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.categories_btn.setIcon(icon5)
        self.categories_btn.setIconSize(QtCore.QSize(35, 35))
        self.categories_btn.setObjectName("categories_btn")
        self.verticalLayout_2.addWidget(self.categories_btn)
        self.favorites_btn = QtWidgets.QPushButton(self.left_widget)
        self.favorites_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.favorites_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:35px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/favorites.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.favorites_btn.setIcon(icon6)
        self.favorites_btn.setIconSize(QtCore.QSize(40, 35))
        self.favorites_btn.setObjectName("favorites_btn")
        self.verticalLayout_2.addWidget(self.favorites_btn)
        self.label_2 = QtWidgets.QLabel(self.left_widget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 italic 16pt \"Perpetua\";\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.mathematics_btn = QtWidgets.QPushButton(self.left_widget)
        self.mathematics_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mathematics_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:30px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/mathematics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mathematics_btn.setIcon(icon7)
        self.mathematics_btn.setIconSize(QtCore.QSize(40, 35))
        self.mathematics_btn.setObjectName("mathematics_btn")
        self.verticalLayout_2.addWidget(self.mathematics_btn)
        self.history_sub_btn = QtWidgets.QPushButton(self.left_widget)
        self.history_sub_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_sub_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:65px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/history_sub.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_sub_btn.setIcon(icon8)
        self.history_sub_btn.setIconSize(QtCore.QSize(35, 35))
        self.history_sub_btn.setObjectName("history_sub_btn")
        self.verticalLayout_2.addWidget(self.history_sub_btn)
        self.science_btn = QtWidgets.QPushButton(self.left_widget)
        self.science_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.science_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:65px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/science.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.science_btn.setIcon(icon9)
        self.science_btn.setIconSize(QtCore.QSize(40, 35))
        self.science_btn.setObjectName("science_btn")
        self.verticalLayout_2.addWidget(self.science_btn)
        self.arts_btn = QtWidgets.QPushButton(self.left_widget)
        self.arts_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arts_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgb(36, 36, 36);\n"
"color: rgb(255, 255, 255);\n"
"background-position:center left;\n"
"padding-right:90px;\n"
"border-radius:0px;\n"
"border-color: rgb(62, 62, 62);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/arts.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.arts_btn.setIcon(icon10)
        self.arts_btn.setIconSize(QtCore.QSize(35, 35))
        self.arts_btn.setObjectName("arts_btn")
        self.verticalLayout_2.addWidget(self.arts_btn)
        self.label_4 = QtWidgets.QLabel(self.left_widget)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 16pt \"Perpetua\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.widget = QtWidgets.QWidget(self.left_widget)
        self.widget.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem3)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.main_2_horizontalLayout.addWidget(self.left_widget)
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setStyleSheet("background-color: rgb(11, 11, 11);")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.main_widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 4, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.main_widget)
        self.widget_3.setMinimumSize(QtCore.QSize(250, 100))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 3, 1, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.main_widget)
        self.widget_5.setMinimumSize(QtCore.QSize(500, 200))
        self.widget_5.setStyleSheet("background-color: rgb(170, 255, 127);")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout.addWidget(self.widget_5, 5, 1, 1, 1)
        self.subject_widget = QtWidgets.QWidget(self.main_widget)
        self.subject_widget.setMinimumSize(QtCore.QSize(100, 50))
        self.subject_widget.setStyleSheet("color: rgb(255, 255, 255);")
        self.subject_widget.setObjectName("subject_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.subject_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.language_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.language_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.language_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.language_btn_2.setObjectName("language_btn_2")
        self.horizontalLayout_3.addWidget(self.language_btn_2)
        self.biology_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.biology_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.biology_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.biology_btn_2.setObjectName("biology_btn_2")
        self.horizontalLayout_3.addWidget(self.biology_btn_2)
        self.evs_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.evs_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.evs_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.evs_btn_2.setObjectName("evs_btn_2")
        self.horizontalLayout_3.addWidget(self.evs_btn_2)
        self.physics_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.physics_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.physics_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.physics_btn_2.setObjectName("physics_btn_2")
        self.horizontalLayout_3.addWidget(self.physics_btn_2)
        self.history_sub2_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.history_sub2_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_sub2_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.history_sub2_btn_2.setObjectName("history_sub2_btn_2")
        self.horizontalLayout_3.addWidget(self.history_sub2_btn_2)
        self.maths_btn_2 = QtWidgets.QPushButton(self.subject_widget)
        self.maths_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maths_btn_2.setStyleSheet("\n"
"\n"
"\n"
"QPushButton{\n"
"background-color:  rgb(62, 62, 62);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:12px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(106, 106, 106);\n"
"}\n"
"")
        self.maths_btn_2.setObjectName("maths_btn_2")
        self.horizontalLayout_3.addWidget(self.maths_btn_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.subject_widget, 2, 1, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.main_widget)
        self.widget_4.setMinimumSize(QtCore.QSize(250, 550))
        self.widget_4.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_8.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 500, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.gridLayout.addWidget(self.widget_4, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.main_widget)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        self.main_2_horizontalLayout.addWidget(self.main_widget)
        self.verticalLayout.addLayout(self.main_2_horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Education 3D"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Search"))
        self.pushButton_2.setText(_translate("Form", "Import  Models"))
        self.home_btn.setText(_translate("Form", "   Home"))
        self.popular_btn.setText(_translate("Form", "   Popular"))
        self.history_btn_2.setText(_translate("Form", " History "))
        self.categories_btn.setText(_translate("Form", "  Categories "))
        self.favorites_btn.setText(_translate("Form", "  Favorites "))
        self.label_2.setText(_translate("Form", "CATEGORIES"))
        self.mathematics_btn.setText(_translate("Form", "  Mathematics "))
        self.history_sub_btn.setText(_translate("Form", "   History "))
        self.science_btn.setText(_translate("Form", "  Science "))
        self.arts_btn.setText(_translate("Form", "  Arts "))
        self.label_4.setText(_translate("Form", "STANDARDS"))
        self.language_btn_2.setText(_translate("Form", "LANGUAGE"))
        self.biology_btn_2.setText(_translate("Form", "BIOLOGY"))
        self.evs_btn_2.setText(_translate("Form", "EVS"))
        self.physics_btn_2.setText(_translate("Form", "PHYSICS"))
        self.history_sub2_btn_2.setText(_translate("Form", "HISTORY"))
        self.maths_btn_2.setText(_translate("Form", "MATHS"))
        self.label_3.setText(_translate("Form", "Explore by Subjects"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
