# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index_demo3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from code import interact
import email
from turtle import st
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import user_details
import json
from os import path




class Ui_Form(object):
    def __init__(self,main_widget,gridLayout_2,gridLayout):
        self.main_widget=main_widget
        self.gridLayout_2=gridLayout_2
        self.gridLayout=gridLayout
        self.data=[]

    def user_page(self):
        import internet
        int=internet.connect() 
        if(int==True):
                com_name=self.company_name_line_edit.text()
                email=self.mail_line_edit.text()
                phone=self.phone_line_edit.text()
                error=''
                import fetch_api_data
                if(com_name!='' and email!='' and phone!=''):
                        
                          
                        fetch_api_data.company_name=com_name
                        fetch_api_data.phone_number=phone
                        fetch_api_data.email=email
                        fetch_api_data.add_data()
                        error=fetch_api_data.er
                        e=error.split('us')
                        
                        if(error==''):
                                        c={"setting_details":fetch_api_data.company_name}
                                        
                                        c_name=fetch_api_data.customer_name
                                        add=fetch_api_data.address1
                                        sta=fetch_api_data.state
                                        city=fetch_api_data.city
                                        pin=fetch_api_data.pincode
                                        print(c_name)
                                        self.data.append(c_name)
                                        self.data.append(add)
                                        self.data.append(sta)
                                        self.data.append(city)
                                        self.data.append(pin)
                                        self.all_widget.hide()
                                        self.load_user=user_details.Ui_Form(self.main_widget,self.gridLayout_2,self.gridLayout,self.data)
                                        self.load_user.setupUi()
                                        json_object = json.dumps(fetch_api_data.datas['details'])
                                        
                                        # print("hell",fetch_api_data.datas['details'])
                                        # Writing to sample.json
                                        try:
                                                with open("setting.json", "w") as outfile:
                                                        outfile.write(json_object)
                                                if path.isfile('setting.json') is False:
                                                        raise Exception("File not found")
                                                with open("setting.json") as outfile:
                                                        obj=json.load(outfile)
                                                obj.update({"company_name":fetch_api_data.company_name})
                                                with open("setting.json", "w") as outfile:
                                                        json.dump(obj,outfile)
                                                print("done")
                                        except:
                                                print("error")
                                        
                        else:
                                        self.error_msg.setText(f'{e[0]}us \n {e[1]}')
                                        self.error_msg.show()
                        
                else:
                        self.error_msg.setText("Please fill all details")
                        self.error_msg.show()
        else:
                self.error_msg.setText("No internet!")
                self.error_msg.show()
    def setupUi(self):
        self.all_widget = QtWidgets.QWidget(self.main_widget)
        self.all_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.all_widget.setObjectName("all_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.all_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_gridLayout = QtWidgets.QGridLayout()
        self.top_gridLayout.setSpacing(0)
        self.top_gridLayout.setObjectName("top_gridLayout")
        self.img_label = QtWidgets.QLabel(self.all_widget)
        self.img_label.setText("")
        self.img_label.setPixmap(QtGui.QPixmap("icon/Untitled_page-0001.jpg"))
        self.img_label.setScaledContents(True)
        self.img_label.setObjectName("img_label")
        self.top_gridLayout.addWidget(self.img_label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.top_gridLayout)
        self.bottom_gridLayout = QtWidgets.QGridLayout()
        self.bottom_gridLayout.setSpacing(0)
        self.bottom_gridLayout.setObjectName("bottom_gridLayout")
        self.label_2 = QtWidgets.QLabel(self.all_widget)
        self.label_2.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.bottom_gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.all_widget)
        self.label_4.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.bottom_gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.all_widget)
        self.label_3.setStyleSheet("color: rgb(166, 166, 166);\n"
"font: 57 10pt \"Poppins Medium\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.bottom_gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.company_name_line_edit = QtWidgets.QLineEdit(self.all_widget)
        self.company_name_line_edit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.company_name_line_edit.setObjectName("company_name_line_edit")
        self.bottom_gridLayout.addWidget(self.company_name_line_edit, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem1, 5, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem4, 0, 5, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem5, 2, 0, 1, 1)
        self.next_btn = QtWidgets.QPushButton(self.all_widget)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.clicked.connect(self.user_page)
        self.next_btn.setStyleSheet("QPushButton{\n"
"\n"
"background-color:  rgb(248,180,100);\n"
"color: rgb(255, 255, 255);\n"
"    \n"
"    font: 63 12pt \"Poppins SemiBold\";\n"
"border-style:outset;\n"
"border-width:0px;\n"
"border-radius:17px;\n"
"border-color: rgb(62, 62, 62);\n"
"padding:6px\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"\n"
"    background-color: rgb(248, 207, 135);\n"
"}\n"
"")
        self.next_btn.setObjectName("next_btn")
        self.bottom_gridLayout.addWidget(self.next_btn, 6, 5, 1, 1)
        self.phone_line_edit = QtWidgets.QLineEdit(self.all_widget)
        self.phone_line_edit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.phone_line_edit.setObjectName("phone_line_edit")
        self.bottom_gridLayout.addWidget(self.phone_line_edit, 2, 3, 1, 1)
        self.mail_line_edit = QtWidgets.QLineEdit(self.all_widget)
        self.mail_line_edit.setStyleSheet("\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"\n"
"border-style:outset;\n"
"border-width:1px;\n"
"border-radius:7px;\n"
"\n"
"border-color: rgb(62, 62, 62);\n"
"font: 57 10pt \"Poppins Medium\";\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QLineEdit:focus{\n"
"/*\n"
"background-color:  rgb(248,180,100);\n"
"*/\n"
"\n"
"    background-color: rgb(248, 221, 158);\n"
"}")
        self.mail_line_edit.setObjectName("mail_line_edit")
        self.error_msg = QtWidgets.QLabel(self.all_widget)
        self.error_msg.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 57 10pt \"Poppins Medium\";")
        # self.error_msg.setAlignment(QtCore.Qt.AlignCenter|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVLeft)
        self.error_msg.setObjectName("error_msg")
        self.error_msg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop|QtCore.Qt.AlignLeft)
        self.bottom_gridLayout.addWidget(self.error_msg, 5, 1, 1, 6)
        self.bottom_gridLayout.addWidget(self.mail_line_edit, 4, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem6, 5, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.bottom_gridLayout.addItem(spacerItem7, 5, 4, 1, 1)
        self.verticalLayout.addLayout(self.bottom_gridLayout)
        self.gridLayout_2.addWidget(self.all_widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 1, 1, 1)
        self.label_2.setText("Phone :")
        self.label_4.setText("Company/Institute Name :")
        self.label_3.setText("Email :")
        self.next_btn.setText("Next")

        # self.retranslateUi(Form)
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
        # self.label_2.setText(_translate("Phone :"))
        # self.label_4.setText(_translate("Company/Institute Name :"))
        # self.label_3.setText(_translate("Email :"))
        # self.next_btn.setText(_translate("Next"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
