# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index_5.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):

    def __init__(self,main_widget,gridLayout_2,gridLayout):
        self.main_widget=main_widget
        self.gridLayout=gridLayout
        self.gridLayout_2=gridLayout_2
    def setupUi(self):
        self.all_widget = QtWidgets.QWidget(self.main_widget)
        self.all_widget.setObjectName("all_widget")
        self.all_widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.all_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_gridLayout = QtWidgets.QGridLayout()
        self.top_gridLayout.setObjectName("top_gridLayout")
        self.label_3 = QtWidgets.QLabel(self.all_widget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("icon/Untitled_page-0004.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.top_gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.top_gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.top_gridLayout)
        self.gridLayout_2.addWidget(self.all_widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)

        self.retranslateUi()
        # QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
import xyz_rc


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Form = QtWidgets.QWidget()
#     ui = Ui_Form()
#     ui.setupUi(Form)
#     Form.show()
#     sys.exit(app.exec_())
